Add support for JsonNode to ´set_fields()`
Graylog2/graylog-plugin-pipeline-processor pull request #228
Opened 2017-11-28 14:23 UTC by joschi

Sometimes users might want to parse and merge the JSON payload of a message
with the Graylog message without knowing the complete structure of the payload
or without having a fixed structure which could be selectively merged by using
the `json_path()` method.

This commit essentially adds the possiblity to create a pipeline rule emulating
the existing JSON extractor:

    rule "json"
    when
      // some condition
    then
      let json = parse_json(to_string($message.some_field));
      set_fields(json);
    end

Refs: https://community.graylog.org/t/parse-unknown-json-with-pipelines/3293/7

2017-12-08 12:56 UTC, bernd commented on plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetFields.java
> +            if (o instanceof Map) {
I don't really like that `set_fields` now knows about `JsonNode` objects. For every new type of object that should be accepted by `set_fields` in the future, we will have to adjust this function. Maybe it's better to add a `to_map` function which sole purpose it is to convert different kind of objects to a `Map`. That makes it reusable and also keeps special object knowledge out of `set_fields`.

2017-12-08 14:59 UTC, joschi commented on plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetFields.java
> +            if (o instanceof Map) {
Having a `to_map` function converting nested structures into a `Map` object would simply move the logic, wouldn't it?

2017-12-08 15:46 UTC, bernd commented on plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetFields.java
> +            if (o instanceof Map) {
Yes, the complexity of converting objects into a `Map` object is still there, but we can then reuse it for other functions instead of having it only in the `set_fields` function. Also `set_fields` doesn't need to be modified.

Also implementing different options for the map conversion becomes easier. For example, the JSON extractor has an option to flatten the keys. The current code in this PR doesn't do that. If we want to implement this, we would have to add a special option to `set_fields` to do that. Having a `to_map` conversion function makes this easier and doesn't poison the API of other functions.

Example:

```
rule "json"
when
  // some condition
then
  let json = parse_json(to_string($message.some_field));
  set_fields(to_map(object: json, flatten: true));
end
```

2018-01-10 09:14 UTC, ka51m1r commented on plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetFields.java
> +            if (o instanceof Map) {
Hi,
how it is going with this PR? 
It would be awesome to have this feature in the near future, because it would be a great improvements for every application which has dynamic logging and logs to json format. (For example every Hybris Environment)

Greetings,
ka51m1r

2018-02-15 11:53 UTC, kroepke approved these changes
lgtm!

2018-02-15 11:54 UTC, kroepke requested changes
actually doesn't, found something after approving

2018-02-15 11:54 UTC, kroepke commented on plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/conversion/MapConversion.java
> +                .description("Converts a value to a long value using its string representation")
Realized this after pressing approve: the description is wrong :)

2018-02-15 11:55 UTC, joschi commented on plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/conversion/MapConversion.java
> +                .description("Converts a value to a long value using its string representation")
Who reads descriptions anyway? :trollface: 

I'll fix it!

2018-02-15 12:12 UTC, kroepke approved these changes

2018-02-15 12:12 UTC, merged